In [2]:
import numpy as np

In [4]:
x=np.array([1,2,3,4])

In [5]:
x

array([1, 2, 3, 4])

In [7]:
x.dtype

dtype('int32')

In [9]:
x.shape

(4,)

In [10]:
m=np.array([[2,3,4],[5,6,7]])

In [11]:
m

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
m.shape

(2, 3)

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.random((2,3))

array([[0.94623954, 0.71873577, 0.62667952],
       [0.59006571, 0.2888695 , 0.10559932]])

In [18]:
x[3]

4

In [19]:
x[0]

1

In [20]:
y=np.array([[1,3,4,4],[2,3,4,56]])

In [21]:
y

array([[ 1,  3,  4,  4],
       [ 2,  3,  4, 56]])

In [22]:
y[1,3]

56

In [23]:
y[:,:3]

array([[1, 3, 4],
       [2, 3, 4]])

In [24]:
y>2

array([[False,  True,  True,  True],
       [False,  True,  True,  True]])

In [25]:
y[y>2]

array([ 3,  4,  4,  3,  4, 56])

In [26]:
b=np.array([[1,3,4,4,5],[2,3,4,56,5]])

In [28]:
b.shape

(2, 5)

In [29]:
b.flatten()

array([ 1,  3,  4,  4,  5,  2,  3,  4, 56,  5])

In [30]:
b.T

array([[ 1,  2],
       [ 3,  3],
       [ 4,  4],
       [ 4, 56],
       [ 5,  5]])

In [31]:
b.reshape([10,1])

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [32]:
b.resize([10,1])

In [33]:
b

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [35]:
v=np.array([9,10])
w=np.array([11,12])

In [36]:
v+w

array([20, 22])

In [37]:
np.add(v,w)

array([20, 22])

In [38]:
v-w

array([-2, -2])

In [39]:
np.subtract(v,w)

array([-2, -2])

In [40]:
v*w

array([ 99, 120])

In [41]:
np.multiply(v,w)

array([ 99, 120])

In [42]:
np.dot(v,w)

219